### ISSUE TITLE
Query about Question 1

### ISSUE THREAD

**Issue by KiranBaktha** [uchicago-python/fall-2017-hw3#1]
Hi in question 1, for the sample input is it okay I return [45] rather than an integer 45 for the filter function. Suppose we wish to use map after filtering for instance, it would be better to return a list right?

**Comment by paulromano** [comment]
Yes, the specifications do say that the `filter` method should return a new `FuncationalList`: "The filter method should accept a function as its only argument and return a FunctionalList"

**Comment by KiranBaktha** [comment]
Sorry I meant the reduce function. So a user cannot chain after reduce function right?
x.reduce(lambda x, y: x+y).map(lambda x: x**2)
So this should not be possible?

**Comment by paulromano** [comment]
That's correct: once a reduction has been performed, further maps and filters cannot be applied because the object returned is not a `FunctionalList`.

**Comment by KiranBaktha** [comment]
Got it Thanks!
